version: '2.3'

services:

  col_container:
    
    image: test_colmap
    container_name: col_container
    working_dir: /code
    build:
      context: ../
      dockerfile: docker/Dockerfile

    # Setup environment variables:
    environment:
      - PYTHONPATH=/code
      # Uncomment the following line to plot images on Linux
      - DISPLAY=unix$DISPLAY

    # Setup the volumes you want to share:
    volumes:
      - ../:/code
      # Uncomment the following line to plot images on Linux
      - /tmp/.X11-unix:/tmp/.X11-unix

    # Uncomment the following line to use an NVIDIA GPU (requires nvidia-docker)
    runtime: nvidia

    # By default this container stay alive without running any command 
    command: tail /dev/null -f
